### ISSUE TITLE
Submitting Buck formula upstream

### ISSUE THREAD

**Issue by amitkot** [ccosby/homebrew-ninja#5]
Did you try submitting Buck formula to upstream?

They claim they will happily accept it:
https://github.com/Homebrew/homebrew/issues/34986

**Comment by ccosby** [comment]
I never got it working properly I don't think. If you need it, I can
reassess. If I recall, buck wants to update itself using git and doesn't
have a true released version that Homebrew requires.

On Thu, Feb 5, 2015 at 9:24 AM, Amit Kotlovski <notifications@github.com>
wrote:

> Did you try submitting Buck formula to upstream?
>
> They claim they will happily accept it:
> Homebrew/homebrew#34986
> <https://github.com/Homebrew/homebrew/issues/34986>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccosby/homebrew-ninja/issues/5>.
>



-- 
chris -at- microcozm -dot- net
== If you wish to make an apple pie from scratch, you must first invent the
universe. - Carl Sagan
=== My crypto keys: http://www.microcozm.net/~ccosby/keys/

**Comment by virl** [comment]
Please implement this.

**Comment by ccosby** [comment]
I don't think anyone ever intends to touch this. Facebook doesn't release buck at a version which makes it a useless endeavor to include in Homebrew.

**Comment by bhamiltoncx** [comment]
FYI,  we did actually start tagging Buck versions, and we now have an official Buck homebrew cask and recipe!

https://buckbuild.com/setup/install.html

https://github.com/facebook/homebrew-fb/blob/master/buck.rb

**Comment by ccosby** [comment]
Thank you, @bhamiltoncx. I'll lock this conversation and leave it here for future Buck users.
