### ISSUE TITLE
Deprecated use of Resource#sha1

### ISSUE THREAD

**Issue by daankets** [ccosby/homebrew-ninja#6]
The below says it all:

> Warning:
> Calling Resource#sha1 is deprecated!
> Use Resource#sha256 instead.
> /usr/local/Library/Taps/ccosby/homebrew-ninja/hpn-ssh.rb:30:in `block in <class:HpnSsh>'
> Please report this to the ccosby/ninja tap!

**Comment by ccosby** [comment]
Thanks for the catch. Fixed.
